### ISSUE TITLE
Error on deploying exemple model on ESP32 NodeMCU board using arduino IDE 

### ISSUE THREAD

**Issue by koulnodji6056** [alcarazolabs/EloquentTinyML-ESP32-Example#1]
Kindly assist me,
I am trying to deploy the same example on my esp32 board but still show that error when I try to upload the code 

see below the error

c:\Users\USER\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c:1: fatal error: opening dependency file C:\Program Files\KMSpico\temp\arduino-sketch-F33A4CC1E6432A75C6D074C31B32EEBB\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c.d: No such file or directory
 #if !defined(ESP32)

**Comment by alcarazolabs** [comment]
> Kindly assist me, I am trying to deploy the same example on my esp32 board but still show that error when I try to upload the code
> 
> see below the error
> 
> c:\Users\USER\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c:1: fatal error: opening dependency file C:\Program Files\KMSpico\temp\arduino-sketch-F33A4CC1E6432A75C6D074C31B32EEBB\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c.d: No such file or directory #if !defined(ESP32)


Same issue reported here https://esp32.com/viewtopic.php?t=25280
I don't know why, sorry. Try another version.

**Comment by koulnodji6056** [comment]
Alright, thank you for quick reply.

I will plan to try with devkit module. Thank you
